### ISSUE TITLE
Checklist

### ISSUE THREAD

**Issue by eduardomp** [eduardomp/carrinho-de-compras#1]
- [ ] Criar as pastas de front end e back end
- [ ] iniciar repositório local e enviar ao github
- [ ] criar o projeto de back end com spring boot
- [ ] adicionar ao repositório
- [ ] criar o projeto de front end com angular
- [ ] adicionar ao repositório
- [ ] Dockerizar back end
- [ ] Dockerizar front end
- [ ] Dockerizar mongodb
- [ ] Criar um docker compose da aplicação
- [ ] README
- [ ] publicar em uma cloud
