### ISSUE TITLE
Checklist

### ISSUE THREAD

**Issue by eduardomp** [eduardomp/carrinho-de-compras#3]
- [ ] Criar projeto angular
- [ ] Modelar entidade Usuario
- [ ] Modelar entidade Itens
- [ ] Modelar entidade Carrinho
- [ ] CRUD Usuario
- [ ] Testes Usuario
- [ ] CRUD Itens
- [ ] Testes Itens
- [ ] CRUD Carrinho
- [ ] Testes Carrinho
